name: Generate Monthly HSK Stories

on:
  schedule:
    - cron: "0 3 1 * *" # Runs at 3:00 UTC on the 1st of each month
  workflow_dispatch: # Also allow manual run from GitHub UI

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: pip install openai

      - name: Generate monthly stories
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python generate_monthly_stories.py

      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only hosting
